<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'bootstrap' => '/bootstrap.php',
                'domain\\measurement' => '/domain/Measurement.php',
                'library\\dic' => '/library/Dic.php',
                'repository\\measurement' => '/repository/Measurement.php',
                'repository\\memory\\measurement' => '/repository/memory/Measurement.php',
                'usecase\\home' => '/usecase/Home.php',
                'usecase\\hometest' => '/tests/usecase/HomeTest.php',
                'usecase\\usecase' => '/usecase/UseCase.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd
